# Generated by Django 4.2.9 on 2025-01-21 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Delivery Status',
                'verbose_name_plural': 'Delivery Statuses',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('delivery_options', models.CharField(choices=[('free', 'free'), ('paid', 'paid')], default='free', max_length=5)),
                ('time_duration', models.IntegerField(default=0, help_text='In minutes.', verbose_name='Time it takes to deliver.')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='DishRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dish Rating',
                'verbose_name_plural': 'Dish Ratings',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(blank=True, max_length=20, verbose_name='Driver id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Driver Name')),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='driver/', verbose_name='vehicle image')),
                ('vehicle_image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=40, null=True)),
                ('vehicle_description', models.TextField(blank=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=40)),
                ('available', models.BooleanField(default=False)),
                ('current_location_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('current_location_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Driver Rating',
                'verbose_name_plural': 'Driver Ratings',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='dishes/', verbose_name='dish image')),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ImageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Image URL',
                'verbose_name_plural': 'Images URLs',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False, verbose_name='Has Paid?')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PersonalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personal Message',
                'verbose_name_plural': 'Personal Messages',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_id', models.CharField(blank=True, max_length=20, verbose_name='Kitchen id')),
                ('image_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='restaurant/', verbose_name='restauarant image')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Restaurant Rating',
                'verbose_name_plural': 'Restaurant Ratings',
            },
        ),
        migrations.CreateModel(
            name='RestaurantWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_bank', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(through='app.CartItem', to='app.dish')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Shopping Carts',
            },
        ),
    ]
