# Generated by Django 4.2.9 on 2025-02-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='delivery_options',
            field=models.CharField(choices=[('free', 'free'), ('paid', 'paid')], default='paid', max_length=5),
        ),
    ]
