# Generated by Django 4.2.9 on 2025-02-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='username')),
                ('role', models.CharField(choices=[('customer', 'customer'), ('chef', 'chef'), ('logistics', 'logistics')], default='customer', max_length=10, verbose_name='Who Am I?')),
                ('provider', models.CharField(choices=[('email', 'email'), ('google', 'google'), ('facebook', 'facebook'), ('twitter', 'twitter')], default='email', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('current_location_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('current_location_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users+', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users+', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=30)),
                ('apartment', models.CharField(blank=True, max_length=50)),
                ('labelled_place', models.CharField(choices=[('HOME', 'HOME'), ('WORK', 'WORK'), ('OTHER', 'OTHER')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
            },
        ),
    ]
